import type { Metadata } from "next";
import { Providers } from "./providers";
import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Test NextUI Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-slate-50 dark:bg-slate-800">
        <Providers>
          <Navbar />
          <main className="flex justify-center px-24">
            <div className="max-w-screen-md min-h-screen flex flex-col items-center gap-8">
              {children}
            </div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
